### ISSUE TITLE
Incorrect implementation of validation algorithm

### ISSUE THREAD

**Issue by intrueder** [Sergiy171/KottansTest#1]
Number `343434343434343` expected to be valid.

**Comment by Sergiy171** [comment]
Isn't it necessary input string to have exactly 16 numbers (as credit card has), grouped or ungrouped?

**Comment by intrueder** [comment]
Different cards have different length of card number: https://en.wikipedia.org/wiki/Bank_card_number

**Comment by Sergiy171** [comment]
Fixed validation.
