### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [Sergiy171/KottansTest#2]
Pass `"3434343434343433"` to `GetCreditCardVendor` method
Expected result: "Unknown" (because number has invalid length)
Actual result: "American Express"

**Comment by Sergiy171** [comment]
What invalid length?
16 numbers.

**Comment by intrueder** [comment]
Read about acceptable length for "American Express" cards here https://en.wikipedia.org/wiki/Bank_card_number

**Comment by Sergiy171** [comment]
Fixed cards with different count of numbers.
