### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [Sergiy171/KottansTest#3]
This is not a new issue, but it reopens #2 

Pass `"50000000000006114"` to `GetCreditCardVendor` method
Expected result: "Unknown" (because number does not pass Luhn check)
Actual result: "Maestro"

**Comment by Sergiy171** [comment]
There was nothing said about Luhn check in GetCreditCardVendor method at the task daclaration. I'll try to add this.

**Comment by Sergiy171** [comment]
Fixed.

**Comment by Sergiy171** [comment]
Some problems with all the project because of this. I'll try to fix it.

**Comment by Sergiy171** [comment]
Fixed problem with using some method overloading.
