### ISSUE TITLE
Issue with valid card number (according to Luhn) but unknown vendor

### ISSUE THREAD

**Issue by intrueder** [Sergiy171/KottansTest#4]
Vendor for `35301113333000001` has been recognized as `Unknown` (correct, 17 digits instead of 16 for JCB)
Such number should not pass validation, but it passes.

**Comment by Sergiy171** [comment]
Why it should not pass validation?
Sources say that this number passes it too:
http://planetcalc.ru/2464/
![2016-05-13_160707](https://cloud.githubusercontent.com/assets/18727935/15248800/ccba5904-1924-11e6-9f5f-88e4871460e7.png)
http://www.dcode.fr/luhn-algorithm
![image](https://cloud.githubusercontent.com/assets/18727935/15248869/2514d4b2-1925-11e6-82bf-e0e271ba6b51.png)

**Comment by Sergiy171** [comment]
I can just do so that if number is not recognized, it is not valid if you're writing about this. But I think that's not correct in terms of Luhn validation.

**Comment by Sergiy171** [comment]
Fixed.

**Comment by intrueder** [comment]
`353011133330000010000000000000000000000000000` number will pass Luhn check too, but is it a normal card number? No, it is just a digit series.. That's what I've asked for - validate only card numbers.

**Comment by Sergiy171** [comment]
Understood.
I've fixed it yesterday by 18:00.
